paginate: 5
paginate_path: "page:num"
gems: [jekyll-paginate]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Flafla2"
      comments: true
      visible: true
  -
    scope:
      path: ""
      type: tags
    values:
      layout: "tag"
collections:
  tags:
    output: true
    permalink: /tags/:path/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false